-- 1. Warehouse create pannuvom (Standard Edition-ku basic enough)
CREATE OR REPLACE WAREHOUSE HR_HACKATHON_WH 
WITH WAREHOUSE_SIZE = 'XSMALL' 
AUTO_SUSPEND = 60 
AUTO_RESUME = TRUE;

-- 2. Database create pannuvom
CREATE OR REPLACE DATABASE HR_ANALYTICS_DB;

-- 3. Iniku namma use panna pora Schema
CREATE OR REPLACE SCHEMA HR_DATA;

-- Employee Table
CREATE OR REPLACE TABLE EMPLOYEE_DETAILS (
    EMP_ID INT PRIMARY KEY,
    NAME STRING,
    DEPARTMENT STRING,
    DESIGNATION STRING,
    JOINING_DATE DATE,
    CITY STRING
);

-- Performance & Attrition Table (Fact Table)
CREATE OR REPLACE TABLE PERFORMANCE_DATA (
    EMP_ID INT,
    ATTENDANCE_PERCENTAGE FLOAT,
    WORKING_HOURS FLOAT,
    PERFORMANCE_SCORE INT, -- 1 to 10
    ATTRITION_RISK_SCORE FLOAT,
    STATUS STRING
);



INSERT INTO EMPLOYEE_DETAILS (EMP_ID, NAME, DEPARTMENT, DESIGNATION, JOINING_DATE, CITY)
SELECT 
    100 + SEQ4() AS EMP_ID,
    'Employee_' || (100 + SEQ4()) AS NAME,
    CASE 
        WHEN SEQ4() % 4 = 0 THEN 'IT'
        WHEN SEQ4() % 4 = 1 THEN 'HR'
        WHEN SEQ4() % 4 = 2 THEN 'Sales'
        ELSE 'Marketing'
    END AS DEPARTMENT,
    CASE 
        WHEN SEQ4() % 3 = 0 THEN 'Senior Analyst'
        WHEN SEQ4() % 3 = 1 THEN 'Manager'
        ELSE 'Associate'
    END AS DESIGNATION,
    DATEADD(day, -UNIFORM(1, 1000, RANDOM()), CURRENT_DATE()) AS JOINING_DATE,
    CASE 
        WHEN SEQ4() % 3 = 0 THEN 'Chennai'
        WHEN SEQ4() % 3 = 1 THEN 'Bangalore'
        ELSE 'Hyderabad'
    END AS CITY
FROM TABLE(GENERATOR(ROWCOUNT => 300));

SELECT * FROM EMPLOYEE_DETAILS;

INSERT INTO PERFORMANCE_DATA (EMP_ID, ATTENDANCE_PERCENTAGE, WORKING_HOURS, PERFORMANCE_SCORE, ATTRITION_RISK_SCORE, STATUS)
SELECT 
    100 + SEQ4() AS EMP_ID,
    UNIFORM(70, 100, RANDOM()) AS ATTENDANCE_PERCENTAGE, -- 70% to 100%
    UNIFORM(7, 10, RANDOM()) AS WORKING_HOURS, -- 7 to 10 hours
    UNIFORM(1, 10, RANDOM()) AS PERFORMANCE_SCORE, -- 1 to 10 scale
    ROUND(UNIFORM(0, 1, RANDOM(1)), 2) AS ATTRITION_RISK_SCORE, -- 0.0 to 1.0
    CASE 
        WHEN UNIFORM(1, 10, RANDOM()) > 8 THEN 'Exited' 
        ELSE 'Active' 
    END AS STATUS
FROM TABLE(GENERATOR(ROWCOUNT => 300));


SELECT * FROM PERFORMANCE_DATA;


-- Join and Aggregate Query
SELECT 
    E.DEPARTMENT, 
    COUNT(E.EMP_ID) AS TOTAL_EMPLOYEES,
    ROUND(AVG(P.PERFORMANCE_SCORE), 2) AS AVG_PERFORMANCE,
    MAX(P.ATTRITION_RISK_SCORE) AS MAX_RISK
FROM EMPLOYEE_DETAILS E
JOIN PERFORMANCE_DATA P ON E.EMP_ID = P.EMP_ID
GROUP BY E.DEPARTMENT;



-- 1. Create a table for JSON
CREATE OR REPLACE TABLE RAW_HR_JSON (JSON_DATA VARIANT);

-- 2. Insert dummy JSON data
INSERT INTO RAW_HR_JSON 
SELECT PARSE_JSON('{"dept": "IT", "skills": ["SQL", "Snowflake", "PowerBI"], "headcount": 120}');

-- 3. JSON Flatten Query
SELECT 
    JSON_DATA:dept::STRING AS DEPARTMENT_NAME,
    f.value::STRING AS SKILLS
FROM RAW_HR_JSON,
LATERAL FLATTEN(input => JSON_DATA:skills) f;


-- Stream create pannuvom
CREATE OR REPLACE STREAM EMP_DATA_STREAM ON TABLE EMPLOYEE_DETAILS;

-- Task create pannuvom (Every 5 minutes check pannum)
CREATE OR REPLACE TASK REFRESH_HR_ANALYTICS_TASK
WAREHOUSE = 'HR_HACKATHON_WH'
SCHEDULE = '5 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('EMP_DATA_STREAM')
AS 
INSERT INTO PERFORMANCE_DATA (EMP_ID, PERFORMANCE_SCORE) VALUES (999, 5); -- Dummy action

-- Task-ah start panna
ALTER TASK REFRESH_HR_ANALYTICS_TASK RESUME;


-- View iruka nu check panna
SHOW VIEWS LIKE 'HR_ANALYTICS_REPORT_VIEW' IN SCHEMA HR_ANALYTICS_DB.HR_DATA;

-- Oru vela view illana, marubadiyum oru vaati idha run pannu (Full Database Path-oda)
CREATE OR REPLACE VIEW HR_ANALYTICS_DB.HR_DATA.HR_ANALYTICS_REPORT_VIEW AS
SELECT 
    E.EMP_ID, E.NAME, E.DEPARTMENT, E.DESIGNATION, E.CITY,
    P.ATTENDANCE_PERCENTAGE, P.WORKING_HOURS, P.PERFORMANCE_SCORE, 
    P.ATTRITION_RISK_SCORE, P.STATUS,
    CASE 
        WHEN P.ATTRITION_RISK_SCORE > 0.7 THEN 'Critical'
        WHEN P.ATTRITION_RISK_SCORE BETWEEN 0.4 AND 0.7 THEN 'Warning'
        ELSE 'Stable'
    END AS RISK_CATEGORY
FROM HR_ANALYTICS_DB.HR_DATA.EMPLOYEE_DETAILS E
JOIN HR_ANALYTICS_DB.HR_DATA.PERFORMANCE_DATA P ON E.EMP_ID = P.EMP_ID;

SELECT * FROM HR_ANALYTICS_DB.HR_DATA.HR_ANALYTICS_REPORT_VIEW LIMIT 5;
